In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [2]:
# Load CSV file
df = pd.read_csv("statistics.csv")

# Show first rows
df.head()

             Statistic                    Value
0           Start Date  2015-01-01 00:00:00 UTC
1             End Date  2025-01-01 00:00:00 UTC
2          Total Posts                      466
3  Total Keyword Posts                      222
4       Total Comments                    13464

In [3]:
# Dataset information
df.info()

# Check for missing values
df.isnull().sum()

# Describe statistics
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Statistic  12 non-null     str
 1   Value      12 non-null     str
dtypes: str(2)
memory usage: 747.0 bytes

         Statistic                    Value
count           12                       12
unique          12                       12
top     Start Date  2015-01-01 00:00:00 UTC
freq             1                        1

In [4]:
# Select numeric columns
X = df.select_dtypes(include=[np.number])

# Display sample
X.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [6]:
import numpy as np

print("Type:", type(X))
print("Shape:", getattr(X, "shape", None))
print("Empty:", X is None or (hasattr(X, "empty") and X.empty))

Type: <class 'pandas.DataFrame'>
Shape: (12, 0)
Empty: True

In [10]:
print(X)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
type(X)

pandas.DataFrame

In [15]:
df.columns

Index(['Statistic', 'Value'], dtype='str')

In [16]:
print(df.columns)

Index(['Statistic', 'Value'], dtype='str')

In [18]:
print(dir())

['In', 'KMeans', 'Out', 'StandardScaler', 'X', '_', '_11', '_15', '_2', '_3', '_4', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__session__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'df', 'exit', 'get_ipython', 'i', 'kmeans', 'np', 'open', 'pd', 'plt', 'quit', 'scaler', 'wcss']

In [22]:
df.columns

Index(['Statistic', 'Value'], dtype='str')

In [23]:
df.columns = df.columns.str.strip()