In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("mammographic.csv")

# View first rows
df.head()

          961    5  begnin  malignant
5.0 67.0  3.0  5.0     3.0          1
4.0 43.0  1.0  1.0     NaN          1
5.0 58.0  4.0  5.0     3.0          1
4.0 28.0  1.0  1.0     3.0          0
5.0 74.0  1.0  5.0     NaN          1

In [3]:
# Dataset info
df.info()

# Summary statistics
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
MultiIndex: 961 entries, (np.float64(5.0), np.float64(67.0)) to (np.float64(4.0), np.float64(62.0))
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   961        930 non-null    float64
 1   5          913 non-null    float64
 2   begnin     885 non-null    float64
 3   malignant  961 non-null    int64
dtypes: float64(3), int64(1)
memory usage: 32.6 KB

961          31
5            48
begnin       76
malignant     0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
MultiIndex: 961 entries, (np.float64(5.0), np.float64(67.0)) to (np.float64(4.0), np.float64(62.0))
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   961        930 non-null    float64
 1   5          913 non-null    float64
 2   begnin     885 non-null    float64
 3   malignant  961 non-null    int64
dtypes: float64(3), int64(1)
memory usage: 32.6 KB

In [7]:
print(df.columns)

Index(['961', '5', 'begnin', 'malignant'], dtype='str')

In [10]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [13]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [18]:
print(df.columns)

Index(['961', '5', 'begnin', 'malignant'], dtype='str')

In [24]:
print(df.columns)

Index(['961', '5', 'begnin', 'malignant'], dtype='str')

In [27]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X = np.array([[1,2], [3,4], [5,6]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [30]:
df.head()

          961    5  begnin  malignant
5.0 67.0  3.0  5.0     3.0          1
4.0 43.0  1.0  1.0     NaN          1
5.0 58.0  4.0  5.0     3.0          1
4.0 28.0  1.0  1.0     3.0          0
5.0 74.0  1.0  5.0     NaN          1

In [33]:
df.head()
df.columns

Index(['961', '5', 'begnin', 'malignant'], dtype='str')

In [34]:
print(df.columns)

Index(['961', '5', 'begnin', 'malignant'], dtype='str')

In [37]:
print(df.columns)

Index(['961', '5', 'begnin', 'malignant'], dtype='str')