In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Load dataset
df = pd.read_csv("State Yearly National Statistics.csv")

# View dataset
df.head()

,State,Year,Population,UnemploymentRate,GDP,BachelorDegreeRate,MedianHouseholdIncome
0,California,2018,39557045,4.2,3000000,32.6,71228
1,California,2019,39512223,4.1,3150000,33.1,75235
2,California,2020,39437610,9.3,3200000,33.5,78105
3,California,2021,39237836,7.7,3400000,34.0,81720
4,Texas,2018,28701845,3.9,1800000,29.3,59570

In [4]:
# Check dataset info
df.info()

# Check missing values
df.isnull().sum()

# Drop missing values (example)
df = df.dropna()

# Display summary statistics
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  20 non-null     str
 1   Year                   20 non-null     int64
 2   Population             20 non-null     int64
 3   UnemploymentRate       20 non-null     float64
 4   GDP                    20 non-null     int64
 5   BachelorDegreeRate     20 non-null     float64
 6   MedianHouseholdIncome  20 non-null     int64
dtypes: float64(2), int64(4), str(1)
memory usage: 1.4 KB

,Year,Population,UnemploymentRate,GDP,BachelorDegreeRate,MedianHouseholdIncome
count,20.000000,2.000000e+01,20.000000,2.000000e+01,20.000000,20.000000
mean,2019.500000,2.449585e+07,5.885000,1.792000e+06,32.715000,67920.800000
std,1.147079,9.355459e+06,2.228116,8.279690e+05,2.698396,7358.466464
min,2018.000000,1.258753e+07,3.400000,9.000000e+05,29.100000,55330.000000
25%,2018.750000,1.952005e+07,4.000000,1.037500e+06,30.150000,62765.000000
50%,2019.500000,2.150796e+07,4.700000,1.775000e+06,33.000000,68528.000000
75%,2020.250000,2.924111e+07,7.625000,2.037500e+06,34.125000,72953.500000
max,2021.000000,3.955704e+07,10.000000,3.400000e+06,37.400000,81720.000000

In [6]:
df.head()
df.columns.tolist()

['State',
 'Year',
 'Population',
 'UnemploymentRate',
 'GDP',
 'BachelorDegreeRate',
 'MedianHouseholdIncome']

In [9]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

features = df

In [12]:
print(df.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [14]:
print(df.columns)   # check names
df.columns = df.columns.str.strip()   # remove spaces

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [15]:
df.columns = df.columns.str.strip()

In [19]:
print(df.head())
print(df.columns)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [22]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [27]:
print(df.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [30]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'plt', 'sns', 'KMeans', 'StandardScaler', 'nltk', 'stopwords', 'word_tokenize', 'TfidfVectorizer', '_1', '_i2', '_i3', 'df', '_3', '_i4', '_4', '_i5', '_i6', '_6', '_i7', 'inertia', 'k_range', 'k', 'model', '_i8', 'scaler', '_i9', 'load_iris', 'data', 'features', '_i10', 'kmeans', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', 'stop_words', 'preprocess_text', '_i17', '_i18', '_i19', '_i20', 'vectorizer', '_i21', '_i22', '_22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', 'kmeans_nlp', '_i29', '_i30'])

In [33]:
print(df.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [34]:
for col in df.columns:
    print(f"'{col}'")

'sepal length (cm)'
'sepal width (cm)'
'petal length (cm)'
'petal width (cm)'

In [35]:
print(df.head())
print(df.columns)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [36]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')