In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("State Homelessness Breakdown.csv")

# View dataset
df.head()

,ID,State,Variable,2013,2012,% Change from 2012,Percentage of Total Homeless Populaiton (2013),"Rate per 10,000"
0,Guam - Chronic individuals,Guam,Chronic individuals,51,22,131.82%,4.0%,3.20
1,New York - Chronic individuals,New York,Chronic individuals,"4,045","4,324",-6.45%,5.2%,2.06
2,Maine - Chronic individuals,Maine,Chronic individuals,159,222,-28.38%,5.3%,1.20
3,North Dakota - Chronic individuals,North Dakota,Chronic individuals,110,81,35.80%,5.3%,1.52
4,Delaware - Chronic individuals,Delaware,Chronic individuals,65,84,-22.62%,6.9%,0.70

In [4]:
print(df.columns)

Index(['ID', 'State', 'Variable', '2013', '2012', '%  Change from 2012',
       'Percentage of Total Homeless Populaiton (2013)', 'Rate per 10,000'],
      dtype='str')

In [7]:
df.columns.tolist()

['ID',
 'State',
 'Variable',
 '2013',
 '2012',
 '%  Change from 2012',
 'Percentage of Total Homeless Populaiton (2013)',
 'Rate per 10,000']

In [10]:
df.head()
df.columns

Index(['ID', 'State', 'Variable', '2013', '2012', '%  Change from 2012',
       'Percentage of Total Homeless Populaiton (2013)', 'Rate per 10,000'],
      dtype='str')

In [14]:
df.head()

,ID,State,Variable,2013,2012,% Change from 2012,Percentage of Total Homeless Populaiton (2013),"Rate per 10,000"
0,Guam - Chronic individuals,Guam,Chronic individuals,51,22,131.82%,4.0%,3.20
1,New York - Chronic individuals,New York,Chronic individuals,"4,045","4,324",-6.45%,5.2%,2.06
2,Maine - Chronic individuals,Maine,Chronic individuals,159,222,-28.38%,5.3%,1.20
3,North Dakota - Chronic individuals,North Dakota,Chronic individuals,110,81,35.80%,5.3%,1.52
4,Delaware - Chronic individuals,Delaware,Chronic individuals,65,84,-22.62%,6.9%,0.70

In [16]:
df.isna().sum()

ID                                                  0
State                                               0
Variable                                            0
2013                                                0
2012                                              108
%  Change from 2012                               108
Percentage of Total Homeless Populaiton (2013)    108
Rate per 10,000                                   163
dtype: int64

In [18]:
print(df.columns)

Index(['ID', 'State', 'Variable', '2013', '2012', '%  Change from 2012',
       'Percentage of Total Homeless Populaiton (2013)', 'Rate per 10,000'],
      dtype='str')

In [20]:
df.columns = df.columns.str.strip()

In [22]:
print(list(df.columns))

['ID', 'State', 'Variable', '2013', '2012', '%  Change from 2012', 'Percentage of Total Homeless Populaiton (2013)', 'Rate per 10,000']